### ISSUE TITLE
Threads Error on Heroku, How to Limit Threads?

### ISSUE THREAD

**Issue by evankline** [cardinalblue/rest-more#7] opened 2014-02-13 01:34 UTC
My app is deployed on Heroku and I'm receiving the following error:

`ThreadError (can't create Thread (11))`

I believe this is due to Heroku limiting concurrent threads. Is there anything built into rest-more that would allow me to specify a limit on concurrent threads?

**Comment by godfat** [comment] 2014-02-13 08:35
We'd seen this before on Heroku as well, and it's gone at some point
and I can't yet to say what's the cause of that. I was sure that we
only use under 10 threads, only if Heroku allowed that little
threads... I also suspected it's due to memory issues, but I couldn't
really say that, either.

Could you please estimate how many threads you're using in your
application? I really doubt if this is the cause.

On the other hand, I am indeed thinking about adding some kind of
thread pool support per client in rest-core, so that for example we
could say that we only want 10 threads for Facebook, 5 threads for
Twitter, so on so forth. This is not really for limiting concurrent
threads though, it's more for limiting connections for a certain
service, because Facebook might not allow 100 connections from one
single IP.

**Comment by evankline** [comment] 2014-02-13 09:24
Hey @godfat thanks for getting back to me so quickly. I built a small app for developers to find other developers to collaborate with through GitHub. The app makes calls to the GitHub Search API and only returns users who have 'Available for Hire' checked in their profile. The amount of concurrent threads all depends on the user's search. 

The Search API call does not use threads, however, in order to check if a user returned from the search is 'Available for Hire', another call must be made to the API for each user. Without threads this was taking approximately 1.5 seconds per user. If a search returned 100 users, all 100 users were checked by making 101 calls to the api in a single search. When a smaller result set is returned from the search, there is no error. However, a generic search that returns a large result set throws the error mentioned above.

It doesn't throw the Threads error for 100 users, but it does for the maximum result set, 1000 users. Besides doing an `each_slice(100)` on the response array and iterating over each slice, is there a way to make 100 concurrent calls in intervals of 10 to avoid the error? The iteration throws a timeout error.

Below is the code I'm using to do the hireable check for each user of the search result for a normal search, and I am doing the same thing but with an `each_slice(100)` for when the search is greater or equal to 500 results.

`client = RC::Github.new(access_token: session[:access_token])`
`users = @users.items.map { |user| client.get("users/#{user.login}") }`

**Comment by godfat** [comment] 2014-02-13 10:18
I see, thanks for the detailed explanation. Apparently you're much
more likely to hit Heroku's limit than we were at the time, and this
kind of search would easily to hit the limit on any platform.

This is a perfect example where thread pool is needed. However sorry
that this is not yet implemented. Since I would like to do something
like this a while ago, this is a perfect chance that I should jump
into it and build one.

While you're waiting for me adding this feature, you could do
something like this as a workaround... Oh now I see you updated your
comment with `each_slice`, which is exactly I am going to suggest.
Although I am not sure which timeout error you're referring to. Is it
because it's too slow to do a batch after batch? Then indeed a thread
pool could improve this by doing next request immediately when one
request is done.

Also, persistent connections should also help here. I haven't
implemented this, either...

I'll try to implement thread pool first, probably using an existing
implementation if I find one feasible. If this is not fast enough,
then I would try to implement persistent connections next.

Thanks for using rest-more and sharing your experience. If you would
also like to participate with me, feel free to send me a pull request
or discuss with me further on rest-core, since this feature should
actually go into rest-core instead of rest-more.

**Comment by evankline** [comment] 2014-02-13 18:02
Thanks so much for the advice and no worries about Rest-More not having those features yet, its still a really great gem and has made it extremely easy to use threads. The timeout error I received was an execution error as in  `Timeout::Error - execution expired:`, I'm not sure that helps but I just wanted to specify. I will also look into solutions involving thread pools and persistent connections. Thanks again for your help and for such a great gem.

**Comment by godfat** [comment] 2014-02-14 17:22
Thank you for your compliment and choosing rest-more :D

If you didn't change any defaults, then I think the timeout were
coming from Github didn't respond for a request in 10 seconds. You
could pass `:timeout => 20` when you initialize the client to raise
the limit to 20 seconds. I am not sure if this is desired, though.
Even if we have thread pools and persistent connections, this might
still happen.

**Comment by evankline** [comment] 2014-02-14 19:21
Thanks again for your help, I bumped the timeout to 60 seconds (I know its a lot but I just want to isolate the Threads error problem opposed to the GitHub timeout) and now in development a maximum response of 1000 users works, however, Heroku still throws the Threads error. So at least this isolates the issue.

**Comment by godfat** [comment] 2014-02-21 19:16
ok, I got first working thread pool support. Could you please try it and see if that works for you? It's in [thread-pool branch](https://github.com/godfat/rest-core/tree/thread-pool). Please checkout the commit message for more information. In short, you might want to put something like this when the app loads.

``` ruby
Github.pool_size = 100
```

Pasted it below:

So we introduce RestCore::CLIENT to hold the client class to get the
corresponding thread pool. We want different thread pools for different
clients I assume. By default, we set Client.pool_size to 0 to disable
thread pool, so that we could have unlimited concurrency power.

Additionally, setting Client.pool_size to a negative value, e.g. -1
would be telling rest-core that do not spawn any thread, just do a
blocking call there.

For now, our thread pool would always pre-allocate all threads.
That is, if we set pool_size to 100, it would then spawn 100 threads
upon first call. This might not be desired, but it's much easier to
implement as the first version. Also, currently there's no way to
shutdown the thread pool, so those threads live in the pool would
live forever (until the process is died). This might also not be
desired, but much easier to implement.

We could also implement trimming in the future. That is, if we're
only using a very small number of threads in the pool, we could
slowly shut some threads down, and spawn more whenever we really need.

Summary, for now:
- Client.pool_size =  0 # Spawning a new thread each time.
- Client.pool_size =  9 # Use 9 threads totally for this client.
- Client.pool_size = -1 # Use no additional thread, doing blocking call.

TODO:
- Spawning threads on demand instead of spawning all all the time.
- Automatically trim the thread pool whenever there are idle threads.
- The ability to shutdown the thread pool elegantly.

I'll probably take [puma's thread pool implementation](https://github.com/puma/puma/blob/v2.7.1/lib/puma/thread_pool.rb) as a reference.

**Comment by godfat** [comment] 2014-02-22 08:54
Just realized that this might be a better reference implementation:
https://github.com/jdantonio/concurrent-ruby/blob/master/lib/concurrent/cached_thread_pool.rb

**Comment by evankline** [comment] 2014-02-23 01:04
Hey, just tested my app with the thread-pool branch and it seems to be working, thanks so much!

**Comment by godfat** [comment] 2014-02-23 17:48
Thanks a lot for trying it, too. Glad that it seems to be working for
you. Though there seems still a lot of missing stuffs. The more I dug
into it, the more I realized that timeout is actually quite broken in
rest-core.

For example, since you're using threads, I assume you're not using
eventmachine. Timeout for rest-client was implemented via another
thread. That means, even if we set pool_size to 100, we might be
ending up with using much more threads. 1000.times{ ... } could
actually uses 1000+100 threads in this case, if timeout is actually
long enough before fired.

Also, when spawning threads, we're probably safe (not really, but ok)
to kill them if it's timed out, but we can't really do that in thread
pool, because we want to reuse them. A fixed size thread pool might
probably be ok since we could rebuild dead threads, but it's not safe
to do that in a thread pool which grows on demand. Things are getting
much more complex in this case.

That means, I might not release this soon. I still need to think about
this more. Stay tuned :P

**Comment by godfat** [comment] 2014-05-02 20:50
Hi @evankline, just want to let you know that the development has been moved to https://github.com/godfat/rest-more and I believe the new code in the [thread-pool](https://github.com/godfat/rest-more/tree/thread-pool) branch should be more stable than before.

This would probably be released as 3.0.0 after the documentation are all updated, and a Firebase client would also be added.

**Closed as completed by godfat** 2014-05-02 20:50 UTC
